### ISSUE TITLE
Unable to launch spotify-restore.py

### ISSUE THREAD

**Issue by arifinsalleh** [helpsterTee/spotify-playlists-2-deezer#1]
Hey there, just started trying out this script, but I seem to always be stuck in the step where I have to launch the spotify-restore.py file. I've attached the errors shown in command prompt, so I hope that would help.
![screenshot 54](https://user-images.githubusercontent.com/12503671/44496881-31ccf680-a6a9-11e8-9e32-8c8ac1846dcf.png)

**Comment by marvinborner** [comment]
You need to use Linux or the Windows Linux Subsystem for that as fcntl is not available for Windows.
